title: Esha Dasgupta # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://eshadasgupta.github.io/portfolio/index">About Me</a>  
  <br><br>
  <a href="https://eshadasgupta.github.io/portfolio/education">Education</a>
  <br><br>
  <a href="https://www.linkedin.com/in/esha-dasgupta-5861528a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
